Notebook to investigate the QFT library
==============
here we do the reverse engeneering the tobias programm

In [1]:
import sftrident.qft as qft
import numpy as np
import Konstanten as con
import Grid_cms as grid

/Users/szabo/pyTableTest/venv/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/Users/szabo/pyTableTest/venv/lib/python2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/Users/szabo/pyTableTest/venv/lib/python2.7/site-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/Users/szabo/pyTableTest/venv/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/Users/szabo/pyTableTest/venv/lib/python2.7/site-packages/scipy/sparse/lil.py:19: RuntimeWarning: n

In [2]:

def eps_laser(l):
    return (l==1)*qft.MinkowskiVector( [0,1,0,0] ) + (l==2)*qft.MinkowskiVector( [0,0,1,0] )

def eps_photon(l):
    return (l==1)*qft.MinkowskiVector([0,np.cos(theta_ph)*np.cos(phi_ph),np.cos(theta_ph)*np.sin(phi_ph),-np.sin(theta_ph)])\
           +(l==2)*MinkowskiVector( [0,-np.sin(phi_ph),np.cos(phi_ph),0])


w_laser     = 0.75/con.m
w_photon    = w_laser
w_cms       = w_laser
w           = w_laser
sqrt_s      = 2.*w_laser

pplusp = w_laser

a0            = 1.0
sigma         = 25 #pulse length
w_laser_l     = 1.e0
w_photon_l    = 4.e0
ksi           = con.pi/4.

Genau_theta   = 10
Genau_gamma   = 5

Harmonic_max  = 2


Envelope      = 'cos^2'

m_eff         = con.m*np.sqrt(1+0.5*a0**2)


theta_ph      = 0.
phi_ph        = 0.
phi_pos       = 0.


Abstand   = 2.0

y0_min  = lambda l: np.log ( w_cms/con.m - np.sqrt( w_cms**2/con.m**2 - 1./l ) )
y1_max  = lambda l: np.log ( w_cms/con.m + np.sqrt( w_cms**2/con.m**2 - 1./l ) )

y_z    = qft.parray(np.linspace(y0_min(Harmonic_max + Abstand),y1_max(Harmonic_max + Abstand),Genau_theta),axis=1)[np.newaxis,:]
#y_z = qft.parray(np.array([y_zOLD[0,1]]))[np.newaxis,:]
#y_z = qft.parray(np.log(pplusp/m_perp))

print "yz: %s"%(y_z)
print "yz.shape: %s"%(str(y_z.shape))

#p_perp=qft.parray(1.0)

#m_perp  = sqrt(1 + p_perp**2)
p_perp  = qft.parray(grid.Grid_rap(y_z[0,:], w_cms, 0 , Harmonic_max + Abstand , Genau_gamma , a0)) #p_T
m_perp  = np.sqrt(1 + p_perp**2)
print "pT: %s"%(p_perp)
print "pT.shape: %s"%(str(p_perp.shape))




yz: [[-3.12686725 -2.58604057 -2.04521389 -1.50438721 -0.96356052 -0.42273384
   0.11809284  0.65891953  1.19974621  1.74057289]]
yz.shape: (1, 10)
pT: [[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.17439981 0.33216602 0.52940876 0.69619421 0.69619421
  0.52940876 0.33216602 0.17439981 0.        ]
 [0.         0.34879961 0.66433204 1.05881751 1.39238841 1.39238841
  1.05881751 0.66433204 0.34879961 0.        ]
 [0.         0.52319942 0.99649807 1.58822627 2.08858262 2.08858262
  1.58822627 0.99649807 0.52319942 0.        ]
 [0.         0.69759923 1.32866409 2.11763503 2.78477683 2.78477683
  2.11763503 1.32866409 0.69759923 0.        ]]
pT.shape: (5, 10)


In [3]:
k_laser = qft.MinkowskiVector([w_laser,0,0,-w_laser])
print "k(laser): %s"%np.asarray(k_laser)
n1 = qft.MinkowskiVector([1, np.sin(theta_ph)*np.cos(phi_ph), np.sin(theta_ph)*np.sin(phi_ph), np.cos(theta_ph)])
print "norm vec n (photon): %s"%np.asarray(n1)
k_photon = w_photon*n1
print "k (photon): %s"%np.asarray(k_photon)
p_pos = qft.MinkowskiVector([ m_perp*np.cosh(y_z),
                            p_perp*np.cos(phi_pos),
                            p_perp*np.sin(phi_pos),
                            m_perp*np.sinh(y_z)] )
print "mom Positron: %s"%np.asarray(p_pos)
print "mom0 Positron: %s"%np.asarray(m_perp*np.cosh(y_z))

q_pos = p_pos + (con.m**2*a0**2)/(4.*(k_laser*p_pos))*k_laser # eff Mom Pos


p_el_plus = k_photon.plus_component() - p_pos.plus_component()
p_el_1= k_photon._1() - p_pos._1()
p_el_2 = k_photon._2()                 -     p_pos._2()

p_el_minus = (con.m**2+p_el_1**2+p_el_2**2)/p_el_plus

p_el_0     = 0.5*(p_el_plus + p_el_minus)
p_el_3     = 0.5*(p_el_plus - p_el_minus)
p_el       = qft.MinkowskiVector([ p_el_0, p_el_1 ,p_el_2, p_el_3 ])
#print "mom Electron: %s"%np.asarray(p_el)

eps_m      = eps_laser(1)*np.cos(ksi)-1j*eps_laser(2)*np.sin(ksi)
eps_p      = eps_laser(1)*np.cos(ksi)+1j*eps_laser(2)*np.sin(ksi)

k(laser): [ 1.46771037  0.          0.         -1.46771037]
norm vec n (photon): [1. 0. 0. 1.]
k (photon): [1.46771037 0.         0.         1.46771037]
mom Positron: [[[ 11.42314414   6.67620767   3.9300822    2.36177387   1.50127203
     1.09069053   1.00698107   1.22505653   1.81027254   2.9380141 ]
  [ 11.42314414   6.77697658   4.14122194   2.6723277    1.82926555
     1.3289814    1.13939079   1.29087146   1.83759632   2.9380141 ]
  [ 11.42314414   7.07067182   4.71828763   3.43968225   2.57359605
     1.86974564   1.466565     1.47075017   1.91723261   2.9380141 ]
  [ 11.42314414   7.53476701   5.54825226   4.43263034   3.47640192
     2.52564397   1.88992472   1.72946068   2.04307333   2.9380141 ]
  [ 11.42314414   8.14016912   6.53546587   5.53097898   4.44208661
     3.22722444   2.3582237    2.0371877    2.20722982   2.9380141 ]]

 [[  0.           0.           0.           0.           0.
     0.           0.           0.           0.           0.        ]
  [  0.          

TypeError: Momentum is not on shell: p^2 = [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]